# Simple KISS translation dictionary
MESSAGES = {
    "turn_start": "--- Tura gracza {name} ---",
    "jail_escape_attempt": "Próba ucieczki z więzienia...",
    "jail_free": "{name} wychodzi z więzienia!",
    "rolled_doubles_jail": "{name} wyrzucił drugi dublet pod rząd {rolls} i idzie do więzienia!",
    "rolled_info": "{name} wyrzucił {steps} {rolls}",
    "extra_roll": "{name} wyrzuca dublet — rzuca jeszcze raz!",
    "passed_start": "{name} przechodzi przez Start i otrzymuje {reward}",
    "landed_on": "Wylądował na: {field_name} ({field_type})",
    "country_bonus": "Cały kraj w posiadaniu! Czynsz podwojony do {rent}.",
    "utility_rent": "Czynsz za wodociągi/elektrownie: {steps} (rzut) * {mult} (mnożnik) = {rent}",
    "paying_rent": "Należy do {owner_name}. Płacę czynsz: {rent}",
    "own_property": "Posiadasz tę nieruchomość.",
    "unowned_price": "Nieruchomość na sprzedaż. Cena: {price}",
    "bought_property": "{name} kupił {field_name}",
    "cannot_afford": "{name} nie ma wystarczająco pieniędzy na {field_name}",
    "declined_purchase": "{name} nie kupił {field_name}",
    "no_pending_purchase": "Brak decyzji o zakupie.",
    "purchase_required": "{name} musi najpierw zdecydować o zakupie.",
    "tax_paid": "Podatek: {field_name}, Koszt: {cost}",
    "go_to_jail": "{name} idzie do więzienia!",
    # Trade Messages
    "trade_proposed": "Zaproponowano handel.",
    "no_active_trade": "Brak aktywnego handlu.",
    "waiting_for_other": "Oczekujemy na odpowiedź drugiego gracza.",
    "trade_rejected": "Oferta odrzucona.",
    "counter_sent": "Wysłano kontrofertę.",
    "not_enough_money": "Kupujący nie ma wystarczająco pieniędzy! Odrzucam.",
    "seller_does_not_own": "Sprzedający nie posiada tej nieruchomości. Oferta anulowana.",
    "invalid_price": "Nieprawidłowa cena.",
    "unknown_response": "Nieznana odpowiedź.",
    "trade_success": "Transakcja zakończona! {buyer_name} kupił {property_name} od {seller_name} za {price}$.",
}
