# Simple KISS translation dictionary
MESSAGES = {
    "turn_start": "--- Tura gracza {name} ---",
    "not_your_turn": "Nie twoja kolej.",
    "jail_escape_attempt": "Próba ucieczki z więzienia...",
    "jail_free": "{name} wychodzi z więzienia!",
    "rolled_doubles_jail": "{name} wyrzucił drugi dublet pod rząd {rolls} i idzie do więzienia!",
    "rolled_info": "{name} wyrzucił {steps} {rolls}",
    "extra_roll": "{name} wyrzuca dublet — rzuca jeszcze raz!",
    "passed_start": "{name} przechodzi przez Start i otrzymuje {reward}",
    "landed_on": "Wylądował na: {field_name} ({field_type})",
    "country_bonus": "Cały kraj w posiadaniu! Czynsz podwojony do {rent}.",
    "utility_rent": "Czynsz za wodociągi/elektrownie: {steps} (rzut) * {mult} (mnożnik) = {rent}",
    "paying_rent": "Należy do {owner_name}. Płacę czynsz: {rent}",
    "own_property": "Posiadasz tę nieruchomość.",
    "unowned_price": "Nieruchomość na sprzedaż. Cena: {price}",
    "bought_property": "{name} kupił {field_name}",
    "cannot_afford": "{name} nie ma wystarczająco pieniędzy na {field_name}",
    "declined_purchase": "{name} nie kupił {field_name}. Licytacja się rozpoczyna.",
    "no_pending_purchase": "Brak decyzji o zakupie.",
    "purchase_required": "{name} musi najpierw zdecydować o zakupie.",
    "payment_required": "{name} musi najpierw uregulować płatność.",
    "tax_paid": "Podatek: {field_name}, Koszt: {cost}",
    "go_to_jail": "{name} idzie do więzienia!",
    # Trade Messages
    "trade_proposed": "Zaproponowano handel.",
    "no_active_trade": "Brak aktywnego handlu.",
    "waiting_for_other": "Oczekujemy na odpowiedź drugiego gracza.",
    "trade_rejected": "Oferta odrzucona.",
    "counter_sent": "Wysłano kontrofertę.",
    "not_enough_money": "Kupujący nie ma wystarczająco pieniędzy! Odrzucam.",
    "seller_does_not_own": "Sprzedający nie posiada tej nieruchomości. Oferta anulowana.",
    "invalid_price": "Nieprawidłowa cena.",
    "unknown_response": "Nieznana odpowiedź.",
    "trade_success": "Transakcja zakończona! {buyer_name} kupił {property_name} od {seller_name} za {price}$.",
    # Auction Messages
    "auction_opened": "Licytacja: {field_name}, cena wywoławcza: {price}$",
    "auction_bid": "{name} licytuje {amount}$ za {field_name}",
    "auction_pass": "{name} rezygnuje z licytacji",
    "auction_won": "{name} wygrywa licytację {field_name} za {amount}$",
    "auction_no_bids": "Nikt nie licytował {field_name}. Pole pozostaje własnością banku.",
    "auction_in_progress": "Trwa licytacja. Poczekaj na jej zakończenie.",
    "not_your_auction_turn": "Nie twoja kolej licytacji.",
    "bid_too_low": "Oferta musi być wyższa niż obecna.",
    "cannot_afford_bid": "Nie stać cię na tę ofertę.",
    # Mortgage Messages
    "mortgaged": "{name} zastawia {field_name} za {amount}$",
    "unmortgaged": "{name} wykupuje zastaw {field_name} za {amount}$",
    "cannot_unmortgage": "Nie stać cię na wykup zastawu.",
    "property_already_mortgaged": "Nieruchomość jest już zastawiona.",
    "property_not_mortgaged": "Nieruchomość nie jest zastawiona.",
    "property_not_owned": "Nie posiadasz tej nieruchomości.",
    "property_mortgaged_no_rent": "Nieruchomość zastawiona — brak czynszu.",
    "cannot_trade_mortgaged": "Nie można handlować zastawioną nieruchomością.",
    "cannot_afford_rent": "{name} nie stać na czynsz {rent}$ dla {owner_name}. Zastaw nieruchomość!",
    "cannot_afford_tax": "{name} nie stać na podatek {cost}$ za {field_name}. Zastaw nieruchomość!",
    "still_cannot_afford": "{name} nadal nie stać na {amount}$ ({reason}).",
}
